Go live w/ Reserve site re-design
mento-protocol/reserve-site pull request #100
Opened 2024-07-25 08:04 UTC by denviljclarke

### Description

This PR merges dev into the main branch, adding all the re-design changes to the reserve site

2024-07-25 08:28 UTC, olenovyk approved these changes
LGTM!

2024-07-25 08:54 UTC, chapati23 requested changes
a few things that look off compared to design, screenshots posted in the previous PR that got merged while I was just posting them: https://github.com/mento-protocol/reserve-site/pull/99

2024-07-26 08:47 UTC, chapati23 requested changes
last one i swear

2024-07-26 08:47 UTC, chapati23 commented on src/components/ReserveComposition.tsx
> +                      {item.token}
token should also be 22px 

<img width="467" alt="image" src="https://github.com/user-attachments/assets/a223519e-dc77-4ec7-b301-ef04dc5f66a6">

2024-07-26 11:44 UTC, RyRy79261 approved these changes
LGTM based off @chapati23 's comments

2024-07-26 12:26 UTC, chapati23 approved these changes
let's go live!

2024-07-26 12:26 UTC, merged