feat: include partial reserve balances in totals
mento-protocol/reserve-site pull request #33
Opened 2023-05-02 23:00 UTC by bayological

### Description

- Updated to include balance of partial reserve in collateral asset amounts displayed on site
- Outstanding supply of stables includes amounts in partial reserve
- Partial reserve address displayed in list of reserve addresses

### Related issues

- Fixes #30

2023-05-03 23:28 UTC, philbow61 approved these changes
LGTM 👍

2023-05-04 10:52 UTC, jmrossy commented on src/addresses.config.ts
> +      return `https://celoscan.io/address/${address}`
Recommend matching other links which use blockscout or updating them

2023-05-04 14:42 UTC, jmrossy approved these changes

2023-05-04 14:58 UTC, bowd requested changes
Unless I'm missing something, the partial reserve will never hold cUSD - just like the normal reserve doesn't and there's no accounting for that in the logic.

It should only affect the tally of collateral assets in the system.

2023-05-04 14:58 UTC, bowd commented on src/providers/Celo.ts
> +}
I don't think we need this.

2023-05-04 14:58 UTC, bowd commented on src/service/stables.ts
> +      units -= partialReserveCUSDAmount
Nor this – basically the partial reserve is equivalent to the normal reserve contract, it will never hold cUSD.

2023-05-05 08:22 UTC, bowd approved these changes

2023-05-05 08:22 UTC, merged