feat: account for safe holdings
mento-protocol/reserve-site pull request #40
Opened 2023-06-27 23:07 UTC by denviljclarke

### Description

This PR expands the reserve collateral count to include ETH, WETH, USDC, and WBTC balances from our Reserve Safe Multisig on Ethereum. I've also made changes to combine tokens on Ethereum under one heading, e.g., list WETH under the ETH label. 

This also required changing how links to the explorers for each address in the token lists are generated. Addresses are now generated on a per holding address basis instead of a per-token basis. 

### Other changes

N/A

### Tested

Tested locally -

USDC & ETH balances now account for current holdings in (0xd0697f70E79476195B742d5aFAb14BE50f98CC1E) 

Used 0xBF72Da2Bd84c5170618Fbe5914B0ECA9638d5eb5 to test WBTC is accounted for
Used 0x2F0b23f53734252Bda2277357e97e1517d6B042A to test WETH is accounted for

Checked that all holding addresses link to their respective explorers 

### Related issues

- Fixes #39 

### Backwards compatibility

N/A

### Documentation

N/A

2023-06-28 21:40 UTC, bayological requested changes
Apart from the one comment, LGTM

2023-06-28 21:40 UTC, bayological commented on src/service/Data.ts
> +  | "CELO"
This should be removed as it's already been declared.

2023-06-28 21:47 UTC, philbow61 approved these changes
LGTM 🚀

2023-06-28 21:57 UTC, bayological approved these changes

2023-06-29 08:50 UTC, ninocomputer approved these changes

2023-06-30 14:46 UTC, denviljclarke commented on src/addresses.config.ts
> +const wallets = {
Yes, the naming makes it easier to reason about that. I'll merge this so the changes can show on the website now and create a new issue for that

2023-06-30 14:47 UTC, merged