Feat: Add footer
mento-protocol/reserve-site pull request #87
Opened 2024-06-25 15:24 UTC by denviljclarke

### Description

This PR adds the Mento footer component, the same component that is used in all of the other Mento UIs

### Other changes

fixed some header padding

### Tested

Ran the site locally in both desktop and mobile layouts
### Related issues

- Fixes #68

2024-06-25 15:30 UTC, RyRy79261 commented
Deployment errors

2024-06-25 18:52 UTC, bayological reviewed
All looks good, the discord icon is slightly misaligned:
![image](https://github.com/mento-protocol/reserve-site/assets/6872903/e8d9bfd3-af8d-4752-bbb8-2dee6e223b89)

2024-06-25 18:55 UTC, bayological reviewed
I also noticed there are some footer links that have been left out(source, team, roadmap, privacy, terms)

Figma:
![image](https://github.com/mento-protocol/reserve-site/assets/6872903/53f79059-e38b-4cf0-8976-d48c8d8c4a10)

Current:
![image](https://github.com/mento-protocol/reserve-site/assets/6872903/d821a69c-278b-4e20-85e2-7da6dcb32987)

2024-06-26 13:24 UTC, chapati23 requested changes
- vertical spacing is off for the footer links
- horizontal spacing is off for the social icons
![Pasted_Image_26_06_24__15_22](https://github.com/mento-protocol/reserve-site/assets/117495/d2b4ef65-195e-45f0-825e-0d57eba00902)

2024-06-26 13:24 UTC, chapati23 commented on src/components/Footer.tsx
> +          Mento © 2024. <br />
are we changing this from the prior dynamic `year` prop to be hardcoded to 2024 now? is that an intentional change?

2024-06-26 19:27 UTC, bayological approved these changes

2024-06-27 08:38 UTC, merged